### ISSUE TITLE
How to initialize session storage?

### ISSUE THREAD

**Issue by Sleepful** [strojure/ring-undertow#3]
From: https://cljdoc.org/d/com.github.strojure/ring-undertow/1.2.0-109/api/strojure.ring-undertow.impl.session#put-session

```
Raises exception if session storage is not initialized in server configuration and session values cannot be set.
```

How to initialize the session storage with `server/start`? 

I cannot mix the ring handlers with the `session` handler from `undertow`

**Comment by Sleepful** [comment]
not sure if I am doing this correctly, but it seems to work 🤷 
```clj
  (:require [strojure.ring-undertow.handler :as ring.handler]
            [strojure.undertow.handler :as handler]
            [strojure.undertow.server :as server])


(defstate server
  :start (server/start
          {:port (conf [:server :port])
           :handler (-> (ring.handler/ring {:ring-handler ring-handler}) (handler/session {}))})
  :stop (server/stop server))
```

e.g. works fine with the [ring session example](https://github.com/ring-clojure/ring/wiki/Sessions):

```clj
(defn handler [{session :session}]
  (let [count   (:count session 0)
        session (assoc session :count (inc count))]
    (-> (response (str "You accessed this page " count " times."))
        (assoc :session session))))
```

**Comment by serioga** [comment]
Yes, you just enable Undertow‘s session management using [session](https://cljdoc.org/d/com.github.strojure/undertow/1.4.0-125/api/strojure.undertow.handler#session) handler, as mentioned in the README.

Please let me know if you need more information.

**Comment by Sleepful** [comment]
It was a bit confusing that it couldn't be done with `ring-undertow/start`, and had a bit of trouble adding the ring handler to `undertow/start` because there were no examples. In case you want to update the docs! 

It works well, but for now I think I will use Jetty because Undertow (the Java library) offers very little control over individual sessions, the configuration seems to apply to all sessions the same, and the redhat documentation is very lacking.
